# Generated by Django 6.0.3 on 2026-03-05 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response latency in milliseconds')),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitored_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apis.monitoredapi')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitored_api'], name='monitoring__monitor_916061_idx'), models.Index(fields=['checked_at'], name='monitoring__checked_f24f31_idx'), models.Index(fields=['monitored_api', 'checked_at'], name='monitoring__monitor_331e3c_idx')],
            },
        ),
    ]
