# Generated by Django 6.0.3 on 2026-03-05 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('expected_status', models.IntegerField(default=200)),
                ('check_interval_seconds', models.IntegerField(default=60)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='apis_monito_organiz_bed7b1_idx'), models.Index(fields=['is_active'], name='apis_monito_is_acti_a6c36c_idx')],
            },
        ),
    ]
